# Generated by Django 6.0.4 on 2026-04-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='quiz_audio/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='audio_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='audio_filesize_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='youtube_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
