"""Generated by Django 6.0.4 on 2026-04-13 02:04."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add transcript metadata fields to the quiz model."""

    dependencies = [
        ('quiz_app', '0002_quiz_audio_file_quiz_audio_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='transcript_language',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='quiz',
            name='transcript_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='quiz',
            name='transcript_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='transcript_text',
            field=models.TextField(blank=True),
        ),
    ]
