# Generated by Django 6.0.4 on 2026-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0003_quiz_transcript_language_quiz_transcript_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="ai_generation_model",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="quiz",
            name="ai_response_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="quiz",
            name="ai_response_text",
            field=models.TextField(blank=True),
        ),
    ]
