"""Generated by Django 6.0.4 on 2026-04-13 11:10."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add AI status and error message fields to quizzes."""

    dependencies = [
        ("quiz_app", "0004_quiz_ai_generation_model_quiz_ai_response_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="ai_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="ai_status",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
